<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: minecraft-wiki
 * Date: Wed, 16 Dec 2015 17:10:51 +0800
 */

$conf['title'] = 'My MCServer Wiki';
$conf['lang'] = 'zh-tw';
$conf['template'] = 'bootstrap3';
$conf['sidebar'] = 'wiki:navigation';
$conf['typography'] = '2';
$conf['tocminheads'] = '4';
$conf['manager'] = '@admin';
$conf['disableactions'] = 'register,resendpwd,profile';
$conf['im_convert'] = '/usr/bin/convert';
$conf['jpg_quality'] = 90;
$conf['refcheck'] = 0;
$conf['subscribers'] = 1;
$conf['registernotify'] = 'op@mine.foo.bar';
$conf['mailfrom'] = 'wiki@mine.foo.bar';
$conf['mailprefix'] = 'MCServer';
$conf['sitemap'] = 1;
$conf['userewrite'] = '2';
$conf['fnencode'] = 'utf-8';
$conf['send404'] = 1;
$conf['proxy']['user'] = '';
$conf['proxy']['pass'] = '';
$conf['plugin']['iframe']['js_ok'] = 1;
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'yeti';
$conf['tpl']['bootstrap3']['customTheme'] = './wiki/bootstrap-css/bootstrap.min.css';
$conf['tpl']['bootstrap3']['showUserHomeLink'] = 0;
$conf['tpl']['bootstrap3']['pageOnPanel'] = 0;
$conf['tpl']['bootstrap3']['tableFullWidth'] = 0;
$conf['tpl']['bootstrap3']['showPageId'] = 0;
$conf['tpl']['bootstrap3']['tocCollapseSubSections'] = 0;
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['tagsOnTop'] = 0;
$conf['tpl']['vector']['vector_sitenotice'] = '0';
$conf['tpl']['vector']['vector_qrcodebox'] = '0';
$conf['tpl']['vector']['vector_donate'] = '0';
$conf['tpl']['dokubook']['closedwiki'] = '1';
$conf['plugin']['authldap']['debug'] = '1';
$conf['plugin']['userhomepage']['set_permissions_others'] = '1';
$conf['plugin']['userhomepage']['group_by_name'] = '0';
$conf['tpl']['arctic']['pagename'] = ':wiki:navigation';
// end auto-generated content